# Generated by Django 4.2 on 2024-09-04 08:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail_custom_code_editor.fields
import wagtail_custom_code_editor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCodeEditorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('code', wagtail_custom_code_editor.fields.CustomCodeEditorField(blank=True, decoder=wagtail_custom_code_editor.validators.CustomCodeEditorDecoder, null=True)),
                ('secondcode', wagtail_custom_code_editor.fields.CustomCodeEditorField(blank=True, decoder=wagtail_custom_code_editor.validators.CustomCodeEditorDecoder, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
